### PR TITLE
Check for all return values of core functions

### PR DESCRIPTION
**Pull request by piFra**
This pull request assures that all functions on src/main/jasm/core compile without a single warning and are formatted and indented as they should be

### CODE REVIEW

**Comment by StefanoBelli** [comment]
Great things, @piFra !
 Are now all write(fd...) and read(fd...) functions properly checked for their return values?

**Comment by piFra** [comment]
Yes now they are. We will not miss anything from now on :)

**Comment by StefanoBelli** [comment]
Ok that's fine... Is your debug build working?

try issuing those commands:
- make clean (and) make cleanbin 
- make debug

then go to _bin-debug_ , after that launch _jasm-debug_ and _jasmcli-debug_ ... 
Are they working?

**Comment by piFra** [comment]
they work, but do not provide ANY debug info

**Pull request merged**
